name: ci-docker-image@ghcr.io

# docker pull ghcr.io/pop-cloud/activities-web:1.0.1
env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_REPOSITORY: pop-cloud
  DOCKER_IMAGE: activities-web
  DOCKER_USER: ci-pop-cloud

  DOCKER_SOURCE: .
  DOCKER_FILE: ./ops/docker/app.dockerfile

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "docker image version as latest,0.0.1"
        required: true
        default: "latest"
      env:
        description: "environment"
        required: true
        default: "test"
  push:
    branches:
      - main
    paths:
      - 'src/**'
jobs:
  release-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=current::$(date +'%F %H:%M:%S')"

      - name: Get current sha
        id: sha
        run: echo "::set-output name=current::$(git rev-parse --short HEAD)"

      - name: Docker Build-Push
        uses: docker/build-push-action@v1
        with:
          path: ${{ env.DOCKER_SOURCE }}
          dockerfile: ${{ env.DOCKER_FILE }}
          username: "ci-pop-cloud"
          password: ${{ secrets.CI_POP_CLOUD_PERSONAL_ACCESS_TOKEN }}
          registry: ghcr.io
          repository: pop-cloud/${{ env.DOCKER_IMAGE }}
          tags: ${{ github.event.inputs.tags }}
          labels: env=${{ github.event.inputs.env }}
          build_args: ENV=${{ github.event.inputs.env }},BUILD=${{ steps.date.outputs.current }},GIT_HASH=${{ steps.sha.outputs.current }}