name: ci-helm-chart@github.io

# helm upgrade -i my lil-app --repo https://pop-cloud.github.io/helm-charts
env:
  SOURCE_DIR: ops
  TARGET_OWNER: pop-cloud
  TARGET_REPO: pop-cloud.github.io
  TARGET_BRANCH: main
  TARGET_TOKEN: ${{ secrets.CI_POP_CLOUD_PERSONAL_ACCESS_TOKEN }}
  TARGET_DIR: helm-charts
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'ops/helm/**'

jobs:
  release-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git-repo
        uses: actions/checkout@v2

      - name: Publish helm-chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          charts_dir: ${{ env.SOURCE_DIR }}
          token: ${{ env.TARGET_TOKEN }}
          owner: ${{ env.TARGET_OWNER }}
          repository: ${{ env.TARGET_REPO }}
          branch: ${{ env.TARGET_BRANCH }}
          target_dir: ${{ env.TARGET_DIR }}
          charts_url: https://${{ env.TARGET_REPO }}
          commit_username: ci-pop-cloud
          commit_email: ci.pop.cloud@gmail.com
